FROM ros:melodic-ros-core

ENV ROS_DISTRO melodic

RUN apt-get update && \
    apt-get install -y ros-${ROS_DISTRO}-rosbridge-server

CMD ["roslaunch","rosbridge_server","rosbridge_websocket.launch"]
